#!/usr/bin/env bash

echo "katzu's Utils Help"
echo ""
echo "  clear"
echo "    - clearing terminal"
echo "  help"
echo "    - Showing up this page"
echo "  nodeflow | nf"
echo "    - creating github workflow that can help you build nodejs project"
echo "  ignored | ig"
echo "    - create git ignored file easily :)"
echo "  liveserver | ls"
echo "    - create live-server scripts with my config"
echo "  update"
echo "    - updating scripts"
echo ""